require:
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3.3
  TargetRailsVersion: 7.0.8.1
  SuggestExtensions: false
  Exclude:
    - db/**/*
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'Gemfile.lock'
  NewCops: enable

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: true
  Max: 15

Metrics/ClassLength:
  Enabled: false

Layout/LineLength:
  Max: 100

Metrics/MethodLength:
  CountComments: false
  Max: 15

Style/ClassAndModuleChildren:
  EnforcedStyle: nested

Layout/DotPosition:
  EnforcedStyle: leading
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: "map"
    collect!: "map!"
    inject: "reduce"
    detect: "find"
    find_all: "select"

Layout/MultilineMethodCallIndentation:
    EnforcedStyle: indented

Style/NumericLiterals:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%r': '{}'
    '%w': '()'
    '%W': '()'
    '%i': '()'
    '%I': '()'

Naming/PredicateName:
  Enabled: true
  NamePrefix:
    - is_
    - not_
    - does_
    - can_
  ForbiddenPrefixes:
    - is_
    - not_
    - does_
    - can_

Style/SignalException:
  EnforcedStyle: only_raise

Style/SingleLineMethods:
  AllowIfMethodIsEmpty: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  EnforcedStyle: predicate

# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/TrailingCommaInHashLiteral
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

# prefer [:foo, :bar, :baz] instead of %i[foo bar baz]
Style/SymbolArray:
  EnforcedStyle: percent
  Enabled: false

Style/WordArray:
  EnforcedStyle: percent
  Enabled: false

# Mixing the styles looks just silly.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys
  EnforcedShorthandSyntax: consistent

Style/DefWithParentheses:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Layout/MultilineAssignmentLayout:
  EnforcedStyle: same_line

Layout/EndAlignment:
  EnforcedStyleAlignWith: variable

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: always_ignore

Style/AsciiComments:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ConditionalAssignment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "config/routes.rb"

Style/FormatStringToken:
  EnforcedStyle: template

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Rails/I18nLocaleTexts:
  Enabled: false
